/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;
import classededados.Matriz;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author eugeniojulio
 */
public class TelaMatriz extends javax.swing.JFrame {
//Atributos
  Matriz matA = null;
  Matriz matB = null;
  DefaultTableModel model = null;
  /**
   * Creates new form TelaMatriz
   */
  public TelaMatriz() {
    initComponents();
    model = (DefaultTableModel) jTableResultado.getModel();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQuantidadeLinhasMA = new javax.swing.JTextField();
        jTextFieldQuantidadeDeColunasMA = new javax.swing.JTextField();
        jButtonCriarMA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaidaMA = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldQuatidadeLinhaMB = new javax.swing.JTextField();
        jTextFieldQuantidadeColunaMB = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSaidaMB = new javax.swing.JTextArea();
        jButtonCRiarMB = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreamResultado = new javax.swing.JTextArea();
        jButtonSomar = new javax.swing.JButton();
        jButtonSubtrair = new javax.swing.JButton();
        jButtonMultiplicar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE MATRIZES");
        setResizable(false);

        jLabel1.setText("MATRIZ A");

        jLabel2.setText("Quantidade de Linhas");

        jLabel3.setText("Quantidade de Colunas");

        jButtonCriarMA.setText("CRIAR");
        jButtonCriarMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarMAActionPerformed(evt);
            }
        });

        jTextAreaSaidaMA.setColumns(20);
        jTextAreaSaidaMA.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaidaMA);

        jLabel4.setText("MATRIZ B");

        jLabel5.setText("Quantidade de Linhas:");

        jLabel6.setText("Quantidade de Colunas");

        jTextFieldQuatidadeLinhaMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuatidadeLinhaMBActionPerformed(evt);
            }
        });

        jTextAreaSaidaMB.setColumns(20);
        jTextAreaSaidaMB.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSaidaMB);

        jButtonCRiarMB.setText("CRIAR");
        jButtonCRiarMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCRiarMBActionPerformed(evt);
            }
        });

        jTextAreamResultado.setColumns(20);
        jTextAreamResultado.setRows(5);
        jScrollPane3.setViewportView(jTextAreamResultado);

        jButtonSomar.setText("+");
        jButtonSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomarActionPerformed(evt);
            }
        });

        jButtonSubtrair.setText("-");
        jButtonSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtrairActionPerformed(evt);
            }
        });

        jButtonMultiplicar.setText("*");
        jButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarActionPerformed(evt);
            }
        });

        jTableResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Triangular Superior", null, null},
                {"Triangular Inferior", null, null},
                {"Simetrica", null, null},
                {"Identidade", null, null}
            },
            new String [] {
                "Itens", "MatrizA", "MatrizB"
            }
        ));
        jScrollPane4.setViewportView(jTableResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldQuantidadeDeColunasMA)
                                    .addComponent(jTextFieldQuantidadeLinhasMA, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSomar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jButtonSubtrair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldQuantidadeColunaMB, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(jTextFieldQuatidadeLinhaMB)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonCriarMA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCRiarMB)
                        .addGap(119, 119, 119))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQuantidadeLinhasMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldQuatidadeLinhaMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldQuantidadeDeColunasMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldQuantidadeColunaMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCriarMA)
                    .addComponent(jButtonCRiarMB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSomar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSubtrair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMultiplicar))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButtonCriarMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarMAActionPerformed
    // TODO add your handling code here:
    try {
      int linhas = Integer.parseInt(jTextFieldQuantidadeLinhasMA.getText());
      int colunas = Integer.parseInt(jTextFieldQuantidadeDeColunasMA.getText());
      matA = new Matriz(linhas, colunas);
      
      for(int linha = 0; linha < matA.getQuantidadeDeLinhas();linha++)
        for(int coluna = 0; coluna < matA.getQuantidadeDeColunas(); coluna++){
          String texto = "Matriz A ["+linha+"]["+coluna+"]";
          int elemento = Integer.parseInt(JOptionPane.showInputDialog(texto));
          matA.setElemento(linha, coluna, elemento);
        }
      
      jTextAreaSaidaMA.setText(matA.getMatriz());
      if(matA.eIdentidade())model.setValueAt("SIM ", 3, 1 );
      else model.setValueAt("NÃO", 3, 1 );
      
      
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro);
    }
    
    
    
  }//GEN-LAST:event_jButtonCriarMAActionPerformed

    private void jTextFieldQuatidadeLinhaMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuatidadeLinhaMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuatidadeLinhaMBActionPerformed

    private void jButtonCRiarMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCRiarMBActionPerformed
        // TODO add your handling code here:
        try {
      int linhas = Integer.parseInt(jTextFieldQuatidadeLinhaMB.getText());
      int colunas = Integer.parseInt(jTextFieldQuantidadeColunaMB.getText());
      matB = new Matriz(linhas, colunas);
      
      for(int linha = 0; linha < matA.getQuantidadeDeLinhas();linha++)
        for(int coluna = 0; coluna < matA.getQuantidadeDeColunas(); coluna++){
          String texto = "Matriz A ["+linha+"]["+coluna+"]";
          int elemento = Integer.parseInt(JOptionPane.showInputDialog(texto));
          matB.setElemento(linha, coluna, elemento);
        }
      
      jTextAreaSaidaMB.setText(matB.getMatriz());
      
      if(matB.eIdentidade())model.setValueAt("SIM ", 3, 2 );
      else model.setValueAt("NÃO", 3, 2 );
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro);
      }
    }//GEN-LAST:event_jButtonCRiarMBActionPerformed

    private void jButtonSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomarActionPerformed
        // TODO add your handling code here:
        try {
            if(matA == null || matB == null) throw new Exception("Matrizes não informadas");
            Matriz aux = matA.adicionar(matB);
            
            jTextAreamResultado.setText(aux.getMatriz());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonSomarActionPerformed

    private void jButtonSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtrairActionPerformed
        // TODO add your handling code here:
        try {
            if(matA == null || matB == null) throw new Exception("Matrizes não informadas");
            Matriz aux = matA.subtrair(matB);
            
            jTextAreamResultado.setText(aux.getMatriz());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonSubtrairActionPerformed

    private void jButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarActionPerformed
        // TODO add your handling code here:
        try {
            if(matA == null || matB == null) throw new Exception("Matrizes não informadas");
            
            Matriz aux = matA.multiplicar(matB);
            
            jTextAreamResultado.setText(aux.getMatriz());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonMultiplicarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaMatriz().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCRiarMB;
    private javax.swing.JButton jButtonCriarMA;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonSomar;
    private javax.swing.JButton jButtonSubtrair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableResultado;
    private javax.swing.JTextArea jTextAreaSaidaMA;
    private javax.swing.JTextArea jTextAreaSaidaMB;
    private javax.swing.JTextArea jTextAreamResultado;
    private javax.swing.JTextField jTextFieldQuantidadeColunaMB;
    private javax.swing.JTextField jTextFieldQuantidadeDeColunasMA;
    private javax.swing.JTextField jTextFieldQuantidadeLinhasMA;
    private javax.swing.JTextField jTextFieldQuatidadeLinhaMB;
    // End of variables declaration//GEN-END:variables
}
